databases:
  - name: calender-app-db
    databaseName: calender_app_db
    user: calender_app_db_user
    region: singapore

services:
  - type: web
    name: calender-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: calender-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false